# Generated by Django 4.2.23 on 2025-08-01 21:45

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("users", "UserRecord")
    for row in MyModel.objects.all():
        row.elrr_id = uuid.uuid4()
        row.save(update_fields=["elrr_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userrecord_elrr_id_alter_userrecord_email'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
