# Generated by Django 4.2.23 on 2025-08-01 21:45

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20250801_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='elrr_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, validators=[django.core.validators.RegexValidator(
                message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
    ]
