# Generated by Django 4.2.25 on 2025-10-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_userrecord_branch_alter_userrecord_rank_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrecord',
            options={'permissions': [('view_user_record_override', 'Can view any user record'), ('view_service_user_record_override', 'Can view service user record')]},
        ),
    ]
