# Generated by Django 4.2.23 on 2025-07-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MMTConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elrr_services_api', models.CharField(help_text='Enter the host url for the ELRR Services to use.', max_length=200)),
                ('elrr_api_key', models.TextField(help_text='Enter the API Key to use for communicating with ELRR Services.')),
                ('xis_api', models.CharField(help_text='Enter the host url for the XIS to use.', max_length=200)),
            ],
        ),
    ]
