# Generated by Django 3.2.23 on 2024-01-24 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCourseArea',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_area', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AreasAndHour',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hours', models.IntegerField()),
                ('academic_areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate_transcript.academiccoursearea')),
            ],
        ),
        migrations.CreateModel(
            name='MilitaryCourse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=250)),
                ('areas_and_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate_transcript.areasandhour')),
            ],
        ),
        migrations.CreateModel(
            name='ACEMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('academic_course_areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate_transcript.academiccoursearea')),
                ('military_courses', models.ManyToManyField(to='generate_transcript.MilitaryCourse')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicInstitute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('institute', models.CharField(max_length=250)),
                ('degree_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate_transcript.degree')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicCourse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('courses', models.CharField(max_length=250)),
                ('academic_course_areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate_transcript.academiccoursearea')),
            ],
        ),
    ]
