# Generated by Django 3.2.23 on 2024-01-25 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCourseArea',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_area', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AreasAndHour',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hours', models.DecimalField(decimal_places=2, help_text='Enter value in hours', max_digits=10)),
                ('academic_course_area', models.ForeignKey(help_text='Choose an academic area from academic course area', on_delete=django.db.models.deletion.CASCADE, related_name='areas_and_hours_set', to='generate_transcript.academiccoursearea')),
            ],
        ),
        migrations.CreateModel(
            name='MilitaryCourse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=250)),
                ('area_and_hours', models.ForeignKey(help_text='Choose an academic area with duration', on_delete=django.db.models.deletion.CASCADE, related_name='degree_set', to='generate_transcript.areasandhour')),
            ],
        ),
        migrations.CreateModel(
            name='ACEMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('academic_course_area', models.ForeignKey(help_text='Choose an academic area from academic course area', on_delete=django.db.models.deletion.CASCADE, related_name='ace_area_set', to='generate_transcript.academiccoursearea')),
                ('military_courses', models.ManyToManyField(help_text='Choose military courses realted to the academic area', related_name='ace_military_set', to='generate_transcript.MilitaryCourse')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicInstitute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('institute', models.CharField(max_length=250)),
                ('degrees', models.ManyToManyField(help_text='Choose a degree offered', related_name='institute_set', to='generate_transcript.Degree')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicCourse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=250)),
                ('academic_course_area', models.ForeignKey(help_text='Choose an academic area from academic course area', on_delete=django.db.models.deletion.CASCADE, related_name='academic_course_set', to='generate_transcript.academiccoursearea')),
            ],
        ),
    ]
