# Generated by Django 3.2.23 on 2024-01-31 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240129_2147'),
        ('generate_transcript', '0001_squashed_0006_auto_20240131_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acemapping',
            name='academic_course_area',
        ),
        migrations.AddField(
            model_name='areasandhour',
            name='military_course',
            field=models.ForeignKey(blank=True, help_text='Choose the relevant military course', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas_and_hours', to='generate_transcript.militarycourse'),
        ),
        migrations.AddField(
            model_name='militarycourse',
            name='areas',
            field=models.ManyToManyField(related_name='mappings', through='generate_transcript.AreasAndHour', to='generate_transcript.AcademicCourseArea'),
        ),
        migrations.AlterField(
            model_name='academiccourse',
            name='academiccoursearea_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='generate_transcript.academiccoursearea'),
        ),
        migrations.AlterField(
            model_name='academiccourse',
            name='code',
            field=models.CharField(help_text='Set course code', max_length=200),
        ),
        migrations.AlterField(
            model_name='academiccourse',
            name='name',
            field=models.CharField(help_text='Set course name', max_length=500),
        ),
        migrations.AlterField(
            model_name='degree',
            name='institute',
            field=models.ForeignKey(help_text='Choose the affiliated Academic Institute', on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='generate_transcript.academicinstitute'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='mos',
            field=models.ManyToManyField(blank=True, help_text='Select valid MOS', related_name='degrees', to='users.MOS'),
        ),
        migrations.AddConstraint(
            model_name='areasandhour',
            constraint=models.UniqueConstraint(fields=('academic_course_area', 'degree', 'military_course'), name='unique_connection'),
        ),
        migrations.AddConstraint(
            model_name='areasandhour',
            constraint=models.CheckConstraint(check=models.Q(('degree', None), ('military_course', None), _connector='OR'), name='only_degree_or_mc'),
        ),
    ]
