# Generated by Django 3.2.23 on 2024-01-25 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('generate_transcript', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userrecord'),
        ),
        migrations.AddField(
            model_name='militarycourse',
            name='user_id',
            field=models.ManyToManyField(blank=True, max_length=250, related_name='military_course', to='users.UserRecord'),
        ),
        migrations.AddField(
            model_name='degree',
            name='area_and_hours',
            field=models.ForeignKey(help_text='Choose an academic area with duration', on_delete=django.db.models.deletion.CASCADE, related_name='degree', to='generate_transcript.areasandhour'),
        ),
        migrations.AddField(
            model_name='areasandhour',
            name='academic_course_area',
            field=models.ForeignKey(help_text='Choose an academic area from academic course area', on_delete=django.db.models.deletion.CASCADE, related_name='areas_and_hours', to='generate_transcript.academiccoursearea'),
        ),
        migrations.AddField(
            model_name='acemapping',
            name='academic_course_area',
            field=models.ForeignKey(help_text='Choose an academic area from academic course area', on_delete=django.db.models.deletion.CASCADE, related_name='ace_area', to='generate_transcript.academiccoursearea'),
        ),
        migrations.AddField(
            model_name='acemapping',
            name='military_courses',
            field=models.ManyToManyField(help_text='Choose military courses realted to the academic area', related_name='ace_military', to='generate_transcript.MilitaryCourse'),
        ),
        migrations.AddField(
            model_name='academicinstitute',
            name='degrees',
            field=models.ManyToManyField(help_text='Choose a degree offered', related_name='institute', to='generate_transcript.Degree'),
        ),
        migrations.AddField(
            model_name='academiccourse',
            name='academic_course_area',
            field=models.ForeignKey(help_text='Choose an academic area from academic course area', on_delete=django.db.models.deletion.CASCADE, related_name='academic_course', to='generate_transcript.academiccoursearea'),
        ),
    ]
