# Generated by Django 3.2.23 on 2024-01-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240129_2147'),
        ('generate_transcript', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccourse',
            name='course',
        ),
        migrations.AddField(
            model_name='academiccourse',
            name='code',
            field=models.CharField(default='', help_text='Set course code', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academiccourse',
            name='name',
            field=models.CharField(default='', help_text='Set course name', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degree',
            name='mos',
            field=models.ManyToManyField(help_text='Select valid MOS', related_name='degrees', to='users.MOS'),
        ),
        migrations.AlterField(
            model_name='acemapping',
            name='military_courses',
            field=models.ManyToManyField(help_text='Choose military courses related to the academic area', related_name='ace_military', to='generate_transcript.MilitaryCourse'),
        ),
    ]
