# Generated by Django 3.2.23 on 2024-02-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0002_auto_20240131_2145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ACEMapping',
        ),
    ]
