# Generated by Django 3.2.23 on 2024-02-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('generate_transcript', '0003_delete_acemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicinstitute',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Select the group that will manage requests for this Institute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_institutes', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='academicinstitute',
            name='institute',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
