# Generated by Django 3.2.23 on 2024-01-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0003_auto_20240129_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areasandhour',
            name='hours',
            field=models.PositiveIntegerField(),
        ),
    ]
