# Generated by Django 3.2.23 on 2024-01-31 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0004_alter_areasandhour_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicinstitute',
            name='degrees',
        ),
        migrations.AddField(
            model_name='degree',
            name='institute',
            field=models.ForeignKey(default=1, help_text='Choose the affiliated Academic Institute', on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='generate_transcript.academicinstitute'),
            preserve_default=False,
        ),
    ]
