# Generated by Django 3.2.23 on 2024-02-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0004_auto_20240207_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militarycourse',
            name='course_id',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AddConstraint(
            model_name='degree',
            constraint=models.UniqueConstraint(fields=('institute', 'degree'), name='unique_degrees'),
        ),
    ]
