# Generated by Django 3.2.25 on 2024-10-16 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generate_transcript', '0005_auto_20240209_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='recipient',
            field=models.ManyToManyField(blank=True, max_length=250, related_name='transcript_recipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
