# Generated by Django 3.2.25 on 2024-10-21 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generate_transcript', '0005_auto_20240209_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250)),
                ('status_update', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate_transcript.transcript')),
            ],
        ),
        migrations.AddField(
            model_name='transcript',
            name='recipient',
            field=models.ManyToManyField(through='generate_transcript.TranscriptStatus', to=settings.AUTH_USER_MODEL),
        ),
    ]
