# Generated by Django 3.2.25 on 2024-11-13 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generate_transcript', '0005_auto_20240209_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Opened', 'Opened'), ('Downloaded', 'Downloaded')], default='Pending', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('academic_institute', models.ForeignKey(blank=True, help_text='Select associated academic institute', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcript_status', to='generate_transcript.academicinstitute')),
                ('recipient', models.ForeignKey(blank=True, help_text='Select associated email address', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcript_status', to=settings.AUTH_USER_MODEL)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate_transcript.transcript')),
            ],
            options={
                'verbose_name_plural': 'Transcript Status',
                'unique_together': {('transcript', 'recipient'), ('transcript', 'academic_institute')},
            },
        ),
    ]
