# Generated by Django 3.2.23 on 2024-01-31 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0005_auto_20240131_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccourse',
            name='academic_course_area',
        ),
        migrations.RemoveField(
            model_name='academiccourse',
            name='id',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='area_and_hours',
        ),
        migrations.AddField(
            model_name='academiccourse',
            name='academiccoursearea_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='generate_transcript.academiccoursearea'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areasandhour',
            name='degree',
            field=models.ForeignKey(blank=True, help_text='Choose the relevant degree', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas_and_hours', to='generate_transcript.degree'),
        ),
        migrations.AddField(
            model_name='degree',
            name='areas',
            field=models.ManyToManyField(related_name='degrees', through='generate_transcript.AreasAndHour', to='generate_transcript.AcademicCourseArea'),
        ),
    ]
