# Generated by Django 3.2.25 on 2024-11-19 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_institute', '0001_initial'),
        ('counseling', '0007_alter_careerplan_academic_institute'),
        ('generate_transcript', '0006_transcriptstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='institute',
            field=models.ForeignKey(help_text='Choose the affiliated Academic Institute', on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='academic_institute.academicinstitute'),
        ),
        migrations.AlterField(
            model_name='transcriptstatus',
            name='academic_institute',
            field=models.ForeignKey(blank=True, help_text='Select associated academic institute', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcript_status', to='academic_institute.academicinstitute'),
        ),
        migrations.DeleteModel(
            name='AcademicInstitute',
        ),
    ]
