# Generated by Django 3.2.25 on 2024-10-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0006_auto_20241021_0121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcriptstatus',
            options={'verbose_name_plural': 'Transcript Status'},
        ),
        migrations.AlterField(
            model_name='transcriptstatus',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Opened', 'Opened'), ('Downloaded', 'Downloaded')], max_length=250),
        ),
    ]
