# Generated by Django 4.2.20 on 2025-04-04 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_enc_ssn_userrecord_ssn'),
        ('generate_transcript', '0017_alter_academiccourse_code_alter_academiccourse_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='militarycourse_user',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='militarycourse_user',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='militarycourse_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='militarycourse_user', to='users.userrecord'),
        ),
    ]
