# Generated by Django 4.2.20 on 2025-03-11 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0017_alter_academiccourse_code_alter_academiccourse_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='militarycourse',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='militaryexperience',
            name='rank_level',
        ),
        migrations.AddField(
            model_name='militarycourse',
            name='version',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AddField(
            model_name='militaryexperience',
            name='LastUpdatedOn',
            field=models.DateField(blank=True, help_text='Set degree start date month and year, January 2050', null=True),
        ),
        migrations.AddField(
            model_name='militaryexperience',
            name='Service',
            field=models.CharField(default='None Assigned', max_length=250, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AddField(
            model_name='militaryexperience',
            name='instruction',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='areasandhour',
            name='level',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
    ]
