# Generated by Django 4.2.20 on 2025-03-18 20:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0018_remove_militarycourse_course_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACEIdentifier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ace_identifier', models.CharField(max_length=500, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')])),
            ],
        ),
        migrations.RenameField(
            model_name='militaryexperience',
            old_name='Service',
            new_name='service',
        ),
        migrations.RemoveField(
            model_name='militarycourse',
            name='version',
        ),
        migrations.RemoveField(
            model_name='militaryexperience',
            name='ACE_identifier',
        ),
        migrations.RemoveField(
            model_name='militaryexperience',
            name='LastUpdatedOn',
        ),
        migrations.AddField(
            model_name='areasandhour',
            name='end_date',
            field=models.DateField(blank=True, help_text='Set degree start date month and year, January 2050', null=True),
        ),
        migrations.AddField(
            model_name='areasandhour',
            name='last_updated_on',
            field=models.DateTimeField(blank=True, help_text='Set degree start date month and year, January 2050', null=True),
        ),
        migrations.AddField(
            model_name='areasandhour',
            name='start_date',
            field=models.DateField(blank=True, help_text='Set degree start date month and year, January 2050', null=True),
        ),
        migrations.AddField(
            model_name='areasandhour',
            name='version',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AddField(
            model_name='areasandhour',
            name='ace_identifier',
            field=models.ForeignKey(default='1', help_text='Choose an ace identifier', on_delete=django.db.models.deletion.CASCADE, related_name='areas_and_hours', to='generate_transcript.aceidentifier'),
            preserve_default=False,
        ),
    ]
