# Generated by Django 4.2.24 on 2025-09-12 20:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0021_remove_militarytestresult_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACEIdentifier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ace_identifier', models.CharField(max_length=500, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')])),
            ],
        ),
        migrations.RemoveField(
            model_name='militarycourse',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='militaryexperience',
            name='ACE_identifier',
        ),
        migrations.AddField(
            model_name='areasandhour',
            name='end_date',
            field=models.DateField(blank=True, help_text='Set degree end date month and year, January 2050', null=True),
        ),
        migrations.AddField(
            model_name='areasandhour',
            name='last_updated_on',
            field=models.DateTimeField(blank=True, help_text='Set degree last updated date month and year, January 2050', null=True),
        ),
        migrations.AddField(
            model_name='areasandhour',
            name='start_date',
            field=models.DateField(blank=True, help_text='Set degree start date month and year, January 2050', null=True),
        ),
        migrations.AddField(
            model_name='areasandhour',
            name='version',
            field=models.CharField(blank=True, max_length=500, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AddField(
            model_name='militarycourse',
            name='version',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AddField(
            model_name='militaryexperience',
            name='instruction',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AddField(
            model_name='militaryexperience',
            name='service',
            field=models.CharField(default='None Assigned', max_length=250, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AddField(
            model_name='militaryexperience',
            name='skill_level',
            field=models.CharField(blank=True, max_length=500, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='areasandhour',
            name='level',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='militarycourse_user',
            name='end_date',
            field=models.DateField(blank=True, help_text='Set degree end date month and year, January 2050', null=True),
        ),
        migrations.AlterField(
            model_name='militaryexperience',
            name='description',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='militaryexperience',
            name='experience_id',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='militaryexperience',
            name='experience_name',
            field=models.CharField(blank=True, default='', max_length=500, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='militaryexperience',
            name='rank',
            field=models.CharField(blank=True, default='', max_length=500, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='militaryexperience',
            name='rank_level',
            field=models.CharField(blank=True, default='', max_length=500, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areasandhour',
            name='ace_identifier',
            field=models.ForeignKey(help_text='Choose an ace identifier', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas_and_hours', to='generate_transcript.aceidentifier'),
        ),
    ]
