# Generated by Django 4.2.25 on 2025-10-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0022_aceidentifier_remove_militarycourse_course_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcript',
            options={'permissions': [('view_transcript_override', 'Can view any transcript')]},
        ),
    ]
