# Generated by Django 4.2.25 on 2025-10-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0023_alter_transcript_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcript',
            options={'permissions': [('view_transcript_override', 'Can view any transcript'), ('view_service_transcript_override', 'Can view service transcript')]},
        ),
        migrations.AlterModelOptions(
            name='transcriptstatus',
            options={'permissions': [('view_transcript_status_override', 'Can view any transcript status'), ('view_service_transcript_status_override', 'Can view service transcript status')], 'verbose_name_plural': 'Transcript Status'},
        ),
    ]
