# Generated by Django 4.2.25 on 2025-10-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0024_alter_transcript_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Transcript Metrics',
                'managed': False,
            },
        ),
    ]
