# Generated by Django 4.2.25 on 2025-11-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0025_transcriptmetrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcriptmetrics',
            options={'managed': False, 'permissions': [('view_transcript_metric_override', 'Can view all transcript metrics'), ('view_service_transcript_metric_override', 'Can view service transcript metrics')], 'verbose_name_plural': 'Transcript Metrics'},
        ),
    ]
