# Generated by Django 4.2.25 on 2025-12-18 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generate_transcript', '0026_alter_transcriptmetrics_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('event', models.CharField(choices=[('va', 'VMET Accessed'), ('la', 'Legacy Accessed'), ('ma', 'MMT Accessed')], help_text='Select event type that occurred', max_length=10)),
                ('initiator', models.ForeignKey(help_text='Select User that triggered the event', on_delete=django.db.models.deletion.CASCADE, related_name='events_triggered', to=settings.AUTH_USER_MODEL)),
                ('transcript', models.ForeignKey(blank=True, help_text='Select Transcript that had the event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='generate_transcript.transcript')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
